### ISSUE TITLE
Follow the API Change

### ISSUE THREAD

**Issue by junichi11** [nbphpcouncil/nb-ci-plugin#4]
https://netbeans.org/bugzilla/show_bug.cgi?id=251327

**Comment by DevotionGeo** [comment]
Do you contribute to NetBeans plugin for CodeIgniter in Britisch Columbia Institute's CodeIgniter repository at https://github.com/bcit-ci/netbeans-plugin ?

**Comment by Monomachus** [comment]
@DevotionGeo AFAIK no

**Comment by junichi11** [comment]
Fixed.
