### ISSUE TITLE
CI_DB_active_record was renamed CI_DB_query_builder

### ISSUE THREAD

**Issue by kenjis** [nbphpcouncil/nb-ci-plugin#5]
Class `CI_DB_active_record` was renamed `CI_DB_query_builder` in CodeIgniter 3.0.

So if I use 3.0, `$db` can't be auto completed.

**Comment by junichi11** [comment]
Fixed.

![nb-ci-issue5](https://cloud.githubusercontent.com/assets/738383/11163618/b02e9bae-8b19-11e5-8c88-749887a49086.png)


@jtakakura I've added the "Version" to the nbproject property. If it is bad, just let me know.

Thanks.

**Comment by kenjis** [comment]
Awesome! Thank you.

**Comment by junichi11** [comment]
You're welcome :)

**Comment by kenjis** [comment]
`CI_Model` still has `CI_DB_active_record`.

~~~
/**
 * @property CI_DB_active_record $db
 * @property CI_DB_forge $dbforge
 * @property CI_Config $config
 * @property CI_Loader $load
 * @property CI_Session $session
 * 
 * @property Install $install
 */
class CI_Model {
	
}
~~~

**Comment by junichi11** [comment]
Sorry, I'll fix it later. Thanks!

**Comment by junichi11** [comment]
Fixed. https://github.com/nbphpcouncil/nb-ci-plugin/releases/tag/v0.5.1

Thanks.

**Comment by PrestonDocks** [comment]
Is it possible to include code completion for models inside of a controller, for example after doing

$this->load->model("mdl_name");

can code completion pull in the methods inside mdl_name? Code Lobster has managed to do, but I don't know how.
