### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by natanfelles** [nbphpcouncil/nb-ci-plugin#7]

**Comment by dcwdeveloper** [comment]
How to use it? X 2
I installed the plugin in Netbeans 8.2 along with the repository plugin, everything looks ok, but it does not work, where is the documentation for this? thanks

**Comment by jst-vikrant** [comment]
Step 1: After successful installation go to  Netbeans->tools->options->php->frameworks & tools->codeigniter->base files and add codeigniter latest zip file then click ok.

Step 2: Add your project or right click on your existing project go to properties->frameworks codeigniter then check the enabled checkbox select version the click ok

Codeigniter icon will appear on project. thats it.

**Comment by dcwdeveloper** [comment]
Never mind, it was as simple as adding 2 files to the project include_path.
No need to download any plugins or any additional configuration, just follow the instructions in the selected answer in this thread: http://stackoverflow.com/questions/9308604/how-to-integrate-codeigniter-with-netbeans-fully

**Comment by natanfelles** [comment]
Thanks for the answers!
